In [41]:
import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv('Datasets/startup.csv')
df

,name,category_list,funding_total_usd,status,country_code,state_code,city,funding_rounds,Investors,Number_of_Investors,Acquirer,Acquirer_Category,Acquirer_Country,Acquirer_State,Acquirer_City,Acquired_Price,Acquired Currency,county,founded_at,Coordinates
0,H2O.ai,Software,33.600000,operating,USA,CA,Mountain View,4.0,Capital One:20000000|Nexus Venture Partners:33...,11.0,-,-,-,-,-,-,-,Santa Clara,2011,37.399364:-122.079517
1,One Inc.,Mobile,1.150050,operating,USA,CA,San Francisco,3.0,Camp One Ventures:150000|CRV:1000050|General C...,12.0,-,-,-,-,-,-,-,San Francisco,2011,37.727239:-123.032229
2,1000 Corks,Software,0.040000,operating,USA,OR,Lake Oswego,1.0,Start-Up Chile:40000,1.0,-,-,-,-,-,-,-,Clackamas,2008,45.412305:-122.699154
3,1000museums.com,Software,6.795451,operating,USA,MA,Lenox,9.0,Alliance of Angels:1289879.0|Converge Venture ...,7.0,-,-,-,-,-,-,-,Berkshire,2008,42.361228:-73.286788
4,Redox,Health,4.000000,operating,USA,WI,Madison,2.0,.406 Ventures:3530000|DreamIt Ventures:470000|...,6.0,-,-,-,-,-,-,-,Dane,2014,43.087806:-89.430121
5,1010data,Software,35.000000,acquired,USA,NY,New York,1.0,Norwest Venture Partners - NVP:35000000,1.0,Advance Publications,Media,USA,NY,Staten Island,500000000,USD,New York,2000,40.664274:-73.9385
6,10sec,Finance,1.600000,operating,USA,CA,San Francisco,2.0,CyberAgent Ventures:1600000,1.0,-,-,-,-,-,-,-,San Francisco,2013,37.727239:-123.032229
7,10X Genomics,Technology,55.000000,operating,USA,CA,Pleasanton,1.0,Foresite Capital:55000000|Paladin Capital Grou...,3.0,-,-,-,-,-,-,-,Alameda,2012,37.666151:-121.87828
8,12 Labs,Health,0.935000,operating,USA,CA,Palo Alto,1.0,Serra Ventures:935000|David Opolon:935000|Evan...,5.0,-,-,-,-,-,-,-,Santa Clara,2014,37.399782:-122.142776
9,121nexus,Health,0.794000,operating,USA,RI,Providence,6.0,"American Pioneer Ventures, Ltd:55000|Betasprin...",6.0,-,-,-,-,-,-,-,Providence,2011,41.823056:-71.418779
10,1366 Technologies,Manufacturing,71.450000,operating,USA,MA,Bedford,9.0,Energy Technology Ventures:15000000|Haiyin Cap...,9.0,-,-,-,-,-,-,-,Middlesex,2007,-1
11,140 Proof,Marketing,5.500000,operating,USA,CA,San Francisco,2.0,BlueRun Ventures:5500000.0|Founders Fund:55000...,4.0,-,-,-,-,-,-,-,San Francisco,2010,37.727239:-123.032229
12,140Fire,Marketing,0.500000,operating,USA,CA,Santa Monica,1.0,Y Combinator:500000,1.0,-,-,-,-,-,-,-,Los Angeles,2010,34.023413:-118.481666
13,15Five,Software,3.400000,operating,USA,CA,San Francisco,3.0,500 Startups:1000000|DominateFund:1000000|Jump...,14.0,-,-,-,-,-,-,-,San Francisco,2011,37.727239:-123.032229
14,170 Systems,Software,14.000000,acquired,USA,MA,Bedford,1.0,Polaris Partners:14000000,1.0,Kofax,Software,USA,CA,Irvine,43000000,USD,Middlesex,1990,-1
15,17hats,Software,5.250000,operating,USA,CA,Los Angeles,2.0,Wavemaker Partners:5250000.0,1.0,-,-,-,-,-,-,-,Los Angeles,2014,34.019394:-118.410825
16,One Block Off the Grid (1BOG),Technology,5.000000,closed,USA,CA,San Francisco,1.0,New Enterprise Associates:5000000,1.0,-,-,-,-,-,-,-,San Francisco,2008,37.727239:-123.032229
17,1CommMedical,Health,2.500000,operating,USA,IA,Ankeny,1.0,Next Level Ventures:2500000,1.0,-,-,-,-,-,-,-,Polk,2013,41.72789:-93.603196
18,Babyscripts,Health,2.100000,operating,USA,DC,Washington,3.0,1776 Ventures:1900000.0|Ense Group:900000|Kens...,4.0,-,-,-,-,-,-,-,District Of Columbia,2013,38.904149:-77.017094
19,1Life Healthcare,Health,30.000000,operating,USA,CA,San Francisco,1.0,Benchmark:30000000|DAG Ventures:30000000|Googl...,5.0,-,-,-,-,-,-,-,San Francisco,2002,37.727239:-123.032229
20,1Mind,Entertainment,0.500000,operating,USA,NH,Hampton Falls,1.0,eCoast:500000|HardGamma Ventures:500000,2.0,-,-,-,-,-,-,-,Rockingham,2011,-1
21,1st Merchant Funding,Finance,10.000000,operating,USA,FL,Miami,1.0,Bank United:10000000|Gries Investment Funds:10...,2.0,-,-,-,-,-,-,-,Miami-dade,2007,25.775163:-80.208615
22,1stdibs,Finance,117.000000,operating,USA,NY,New York,5.0,Alibaba:15000000|Benchmark:102000000.0|Index V...,4.0,-,-,-,-,-,-,-,New York,2001,40.664274:-73.9385
23,1stGig.com,Finance,0.750000,operating,USA,NY,Saratoga Springs,1.0,First Fairfield Associates:750000,1.0,-,-,-,-,-,-,-,Saratoga,2009,43.06781:-73.777635
24,1World Online,Software,4.000000,operating,USA,CA,San Jose,3.0,AltaIR Capital:2500000|Altair Capital:2500000|...,6.0,-,-,-,-,-,-,-,Santa Clara,2011,37.296867:-121.819306
25,20/20 Gene Systems Inc.,Technology,4.345427,operating,USA,MD,Rockville,3.0,Maryland Venture Fund:150000,1.0,-,-,-,-,-,-,-,Montgomery,2000,39.083647:-77.155618
26,2080 Media,Entertainment,51.507046,operating,USA,GA,Atlanta,7.0,BIP Capital:35700000.0|Hamilton Ventures LLC:2...,5.0,-,-,-,-,-,-,-,Fulton,2008,33.762909:-84.422675
27,20x200,Education,2.800000,operating,USA,NY,New York,2.0,AOL Ventures:2000000|Founder Collective:280000...,11.0,-,-,-,-,-,-,-,New York,2007,40.664274:-73.9385
28,21 Inc,Software,121.050000,operating,USA,CA,San Francisco,2.0,Andreessen Horowitz:116000000|Data Collective:...,10.0,-,-,-,-,-,-,-,San Francisco,2013,37.727239:-123.032229
29,23andMe,Technology,227.049900,operating,USA,CA,Mountain View,8.0,Casdin Capital:115000000|Fidelity Management &...,17.0,-,-,-,-,-,-,-,Santa Clara,2006,37.399364:-122.079517
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13702,Zuznow,Software,0.650000,operating,USA,NY,New York,1.0,Incentive Incubator:650000,1.0,-,-,-,-,-,-,-,New York,2013,37.296867:-121.819306
13703,"ZVerse, Inc.",Software,5.000000,operating,USA,MD,Columbia,2.0,Capital A Partners:3500000|Mosley Ventures:350...,2.0,-,-,-,-,-,-,-,Howard,2013,37.495519:-122.26681
13704,Zyga Technology,Health,75.750000,operating,USA,MN,Minnetonka,8.0,Bridge Bank:15000000|Domain Associates:2700000...,7.0,-,-,-,-,-,-,-,Hennepin,2008,-1
13705,Zymergen,Technology,44.000000,operating,USA,CA,Emeryville,2.0,5 Prime Ventures:44000000|AME Cloud Ventures:4...,9.0,-,-,-,-,-,-,-,Alameda,2013,41.478138:-81.679486
13706,Zymetis,Technology,2.257464,closed,USA,MD,College Park,3.0,Maryland Department of Business and Economic D...,1.0,-,-,-,-,-,-,-,Prince Georges,2006,37.399782:-122.142776
13707,Zynga,Software,866.550786,ipo,USA,CA,San Francisco,9.0,Andreessen Horowitz:15187000|Avalon Ventures:4...,22.0,-,-,-,-,-,-,-,San Francisco,2007,37.727239:-123.032229
13708,Zyngenia,Technology,25.000000,operating,USA,MD,Gaithersburg,1.0,New Enterprise Associates:25000000,1.0,-,-,-,-,-,-,-,Montgomery,2008,40.664274:-73.9385
13709,ZYOMYX,Technology,34.275015,operating,USA,MO,Fremont,4.0,Bill & Melinda Gates Foundation:12000000|Mylan...,3.0,-,-,-,-,-,-,-,Carter,1998,36.227712:-115.264045
13710,Zype,Software,3.300000,operating,USA,NY,New York,2.0,Entrepreneurs Investment Fund:1600000|Revel Pa...,10.0,-,-,-,-,-,-,-,New York,2013,37.727239:-123.032229
13711,Whisk (formerly Zypsee),Sports,2.150000,operating,USA,NY,New York,2.0,ff Venture Capital:2150000,1.0,-,-,-,-,-,-,-,New York,2011,47.620499:-122.350876
13712,Ôasys,Hardware,0.018192,operating,USA,CA,San Francisco,1.0,Startupbootcamp:18192,1.0,-,-,-,-,-,-,-,San Francisco,2014,34.019394:-118.410825
13713,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,47.684664:-122.191466
13714,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,37.296867:-121.819306
13715,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,47.620499:-122.350876
13716,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,37.727239:-123.032229
13717,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,37.56482:-122.250782
13718,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.077219:-75.3041
13719,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,43.106959:-89.50634
13720,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,33.123909:-117.282835
13721,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.664274:-73.9385
13722,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,39.201146:-76.85905
13723,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,44.932582:-93.456549
13724,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,37.838875:-122.297856
13725,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,38.994646:-76.935995
13726,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,37.727239:-123.032229
13727,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,39.118022:-77.232401
13728,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,36.952306:-91.162325
13729,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.664274:-73.9385
13730,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.664274:-73.9385
13731,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,37.727239:-123.032229

In [54]:
# funding_and_dates = df['funding_total_usd'] + df['founded_at']
funding_and_dates = pd.concat([df['funding_total_usd'], df['founded_at']], axis=1).sort_values('founded_at')

In [78]:
# funding_and_dates.plot.line('founded_at', 'funding_total_usd')
new_df = df.sort_values('founded_at')
new_df.plot('founded_at', 'funding_total_usd')
plt.show()

AttributeError: 'FramePlotMethods' object has no attribute 'xkcd'

In [63]:
# ls = []
# for i in list(df_dropped['founded_at'].sort_values()):

# plt.figure(figsize = (20,5) )
# plt.plot(list(df_dropped['founed_at'].sort_values().unique()), ls, 'o')
df_dropped = df.dropna()

ls_software = []
for i in list(df_dropped['founded_at'].sort_values().unique()):
    ls_software.append(df_dropped[(df['founded_at'] == i) & (df_dropped['category_list'] == 'Software')]['funding_total_usd'])
# return ls_software

/Users/jeromeschmidt/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:10: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  # Remove the CWD from sys.path while we load stuff.

In [64]:
print(ls_software)

[5337     40.0
12820    28.0
Name: funding_total_usd, dtype: float64, Series([], Name: funding_total_usd, dtype: float64), Series([], Name: funding_total_usd, dtype: float64), Series([], Name: funding_total_usd, dtype: float64), Series([], Name: funding_total_usd, dtype: float64), Series([], Name: funding_total_usd, dtype: float64), Series([], Name: funding_total_usd, dtype: float64), Series([], Name: funding_total_usd, dtype: float64), Series([], Name: funding_total_usd, dtype: float64), Series([], Name: funding_total_usd, dtype: float64), Series([], Name: funding_total_usd, dtype: float64), Series([], Name: funding_total_usd, dtype: float64), Series([], Name: funding_total_usd, dtype: float64), Series([], Name: funding_total_usd, dtype: float64), Series([], Name: funding_total_usd, dtype: float64), 9846    35.0
Name: funding_total_usd, dtype: float64, Series([], Name: funding_total_usd, dtype: float64), Series([], Name: funding_total_usd, dtype: float64), Series([], Name: funding_total_usd, dtype: float64), Series([], Name: funding_total_usd, dtype: float64), Series([], Name: funding_total_usd, dtype: float64), Series([], Name: funding_total_usd, dtype: float64), Series([], Name: funding_total_usd, dtype: float64), 641    5.0
Name: funding_total_usd, dtype: float64, Series([], Name: funding_total_usd, dtype: float64), 168    10.0
Name: funding_total_usd, dtype: float64, Series([], Name: funding_total_usd, dtype: float64), Series([], Name: funding_total_usd, dtype: float64), Series([], Name: funding_total_usd, dtype: float64), 6529    11.4
Name: funding_total_usd, dtype: float64, Series([], Name: funding_total_usd, dtype: float64), Series([], Name: funding_total_usd, dtype: float64), Series([], Name: funding_total_usd, dtype: float64), Series([], Name: funding_total_usd, dtype: float64), 12541    0.5
Name: funding_total_usd, dtype: float64, 5500    6.0
Name: funding_total_usd, dtype: float64, Series([], Name: funding_total_usd, dtype: float64), Series([], Name: funding_total_usd, dtype: float64), 4378    10.0
Name: funding_total_usd, dtype: float64, Series([], Name: funding_total_usd, dtype: float64), 7943    4.5
Name: funding_total_usd, dtype: float64, 5158      3.0
10241    22.0
Name: funding_total_usd, dtype: float64, Series([], Name: funding_total_usd, dtype: float64), 59    13.0
Name: funding_total_usd, dtype: float64, Series([], Name: funding_total_usd, dtype: float64), 6515    2.5726
Name: funding_total_usd, dtype: float64, 447    12.0
Name: funding_total_usd, dtype: float64, 533    0.75
Name: funding_total_usd, dtype: float64, 787       0.25
902      10.45
2506      3.50
2618    316.00
Name: funding_total_usd, dtype: float64, Series([], Name: funding_total_usd, dtype: float64), Series([], Name: funding_total_usd, dtype: float64), 122        1.0
8609     250.0
8921      20.3
11396     17.0
Name: funding_total_usd, dtype: float64, 876      18.0
1680    750.0
2747    123.0
8552    139.5
Name: funding_total_usd, dtype: float64, 996     100.0
8186      4.0
Name: funding_total_usd, dtype: float64, 2312      30.0
11515    316.0
Name: funding_total_usd, dtype: float64, 1410        13.100
5748         7.000
9633         0.099
10102       20.000
11912        7.500
12748    30079.503
Name: funding_total_usd, dtype: float64, 2425      2.500000
3467     12.862048
4001     47.000000
6640     65.000000
7141      3.000000
10432    69.900000
Name: funding_total_usd, dtype: float64, 384      10.200000
3297     12.679995
4437     25.000000
7145      0.050000
7627     21.799976
12907    32.000000
Name: funding_total_usd, dtype: float64, 50       169.500000
943        2.250000
3107      13.950000
4783      26.787093
7102       1.400000
9535       3.000000
12052      1.000000
12917     18.500000
Name: funding_total_usd, dtype: float64, 160      45.000000
1638     16.680511
10231     5.000000
Name: funding_total_usd, dtype: float64, 1063     10.500000
3202     60.000000
3734      5.067737
6008      3.000000
7735     10.000000
11169    13.000501
11263    12.500000
Name: funding_total_usd, dtype: float64, 1681      6.000000
2302      0.600000
5936     46.750000
6007     75.000000
6711     87.000000
11531    10.000000
12525    21.299674
Name: funding_total_usd, dtype: float64, 14       14.0
610       6.7
6012      5.0
8388    165.0
Name: funding_total_usd, dtype: float64, 4172      33.200000
4779      78.000000
4993     130.272724
6209       2.684000
6674      26.590000
6926       5.000000
8187      11.000000
9261      17.000000
10935     27.000000
13089     13.800001
Name: funding_total_usd, dtype: float64, 586      1.1575
937     30.0000
1104     8.0000
2038     4.2500
3692    15.8000
6305    44.0000
6984    44.0000
8486     7.5000
9319     2.3200
Name: funding_total_usd, dtype: float64, 337      12.0000
2277      6.1170
3471      2.2500
3622     21.9000
4396      4.7750
5960     44.6164
6835      7.6000
9500     12.5000
12108     0.7500
12920    11.4250
Name: funding_total_usd, dtype: float64, 729       3.8
1151     26.5
2658     11.7
3615     10.0
4811      5.0
5865      4.5
5909      9.0
8158     60.5
9603      5.5
11315    30.5
11562    36.7
11881    60.0
12518     2.5
13111    18.0
Name: funding_total_usd, dtype: float64, 1180       9.000000
1285       7.500000
1819       8.080000
1998       8.000000
2963      13.500000
3016      36.102807
3666       2.500000
3722      21.445695
4658      15.000000
6900       0.100000
7022       1.000000
7764      40.800000
7900       7.000000
8959      49.500000
9083      86.500000
10561     12.075000
10667     14.500000
10679     67.933006
10960    105.000000
12123     15.500000
12312    146.000000
13107      5.235714
13391     50.000000
Name: funding_total_usd, dtype: float64, 815       70.978783
990       25.000000
1308       5.000000
2014      11.350000
2258      20.300000
2264       3.750000
2582      52.450000
2851       8.000000
2888       4.500000
2933       9.840000
3630       2.500000
3649       8.362387
3683       6.500000
3795      40.000000
4156       4.400000
4343      40.000000
4957     291.297000
5081       8.050000
5712       4.200000
5977      22.000000
7925      98.000000
7952      12.000000
8200      31.100000
8292       7.000000
8894      65.277712
8942      22.498160
9219      31.720203
9796      40.000000
9806      72.000000
9912      20.000000
10237     30.000000
10895     15.000000
10944     22.357298
11840     29.500000
11931      2.100000
12658      9.000000
12727     47.275000
13029     25.000000
Name: funding_total_usd, dtype: float64, 109        4.400000
362       45.400000
413       12.265000
483       14.253000
1112      33.000000
1252      22.813005
1572      12.600000
2241      95.899999
2339      79.000000
2488      20.000000
2538      14.200000
2878       2.200000
2894      14.500000
3121      29.000000
3197       4.000000
3542      30.000000
3627      20.500000
3660       4.550000
3772      68.800000
4060       6.000000
4103      29.957650
4713       2.000000
5639      10.000000
5651      12.000000
5785      56.000000
5798       8.300000
5899       8.000000
6056      10.964643
6078     100.000000
6145       4.000000
6232      56.600000
7043      14.500000
7049       6.000000
7252      28.400000
7390      42.500000
7938      13.000000
7939      30.000000
8761      10.000000
8782      25.000000
9569       4.100000
10223     35.000000
10736     23.000000
11113     23.000000
11658      2.830000
11675      9.100000
11878     10.451998
12218      9.800000
12299      2.100000
12330      8.301265
12374     37.000000
12655     24.000000
12977     45.200000
13110    108.912913
13186      5.000000
13206     45.000000
13369     10.005118
Name: funding_total_usd, dtype: float64, 35        85.000000
180        2.100000
208      113.616859
209       43.600000
257        2.400000
408       40.000000
455        2.000000
797        4.000000
835       14.500000
914        0.622000
1106      22.900000
1138      12.200000
1205      15.000000
1294      34.400000
1892      44.000000
2374      19.700000
2467       3.000000
2528      36.185166
2718      53.700000
3217     487.358426
3414      26.000000
3556      46.000000
3780       4.500000
3788       1.604597
3819      51.500000
3870      14.000000
3980      46.000000
3993       3.671000
4003     280.000000
4315      97.200000
            ...
7517      23.888600
7668       2.300000
8051      35.000000
8074       3.000000
8127      54.324900
8250      46.750000
8524       1.170000
8542      11.800000
8966      16.000000
9347      21.250027
9579       8.900000
9620      11.500000
9820      52.000000
10234      9.500000
10399      6.000000
10435     15.000000
10807      1.650000
11587      4.650000
11631     12.800000
11835     14.500000
12051      3.436185
12339     27.400000
12642     42.150000
12668     19.500000
12746     29.900000
12959    368.500000
13174     38.000000
13242     15.000000
13315     32.000000
13420    153.764344
Name: funding_total_usd, Length: 72, dtype: float64, 54        148.000000
149        13.410901
340        20.000000
441        27.500000
538        22.400000
594        31.000000
711        15.000000
780        47.499994
795       154.000000
886         8.000000
944        58.900000
1062       18.000000
1073        1.280000
1108       21.000000
1165       33.500000
1193       12.200000
1269        1.000000
1573       13.500150
1695       13.500000
1791       14.000000
1890       57.000000
1919        0.705000
2004       92.885563
2091      123.000000
2162      120.000000
2236        1.000000
2238        9.250000
2293        6.084516
2388        4.500000
2411       38.225000
            ...
10685       2.200000
11055     217.500000
11089      74.560000
11198       6.500000
11228      80.900000
11310     247.700000
11345      15.000000
11563    1150.000000
11803      18.250000
11821      14.000000
11828      50.000000
11850      51.000000
12185      12.750000
12461      16.000000
12489       4.000000
12650      11.000000
12690       2.000000
12737      46.799996
12789      65.000000
12940       7.000000
12952       3.500000
12982      90.000000
13202      15.500000
13324      57.400000
13354      45.000000
13359      21.000000
13367      22.655660
13413      23.500000
13464      31.361000
13622      49.600000
Name: funding_total_usd, Length: 140, dtype: float64, 5         35.000000
175        3.315000
191       13.600000
224        2.000000
479       11.000000
484      163.000000
542      110.000000
645       25.500000
743        9.700000
859       39.868500
882       26.914000
896       47.952301
910       30.350000
936       45.550000
987       34.860000
1019      53.209289
1051      39.200000
1058       5.000000
1109       2.500000
1150     100.000000
1192      26.000000
1298      14.000000
1302       8.000000
1306      35.869729
1555      40.800000
1564       1.700000
1578      51.275260
1625      13.500000
1627       6.000000
1640       3.000000
            ...
10076      8.200000
10171     10.000000
10186      2.300000
10187      9.453766
10226      0.380000
10299     12.000000
10534     39.000000
10726     10.000000
10731     56.494609
10800     32.000000
11346     48.000000
11375     42.500000
11747     25.950000
11849     48.260819
11862     43.500000
11869     19.800000
11884     32.400000
11896      8.000000
11902      6.000000
11980      4.300000
12124      5.000000
12305     40.100000
12839      8.025000
13101      3.000000
13203     14.000000
13215     10.000000
13254     50.461490
13327     60.000000
13399      9.000000
13669      7.000000
Name: funding_total_usd, Length: 178, dtype: float64, 407        7.000000
443       20.000000
525        6.000000
573      135.000000
918        7.964826
965        5.250000
992        7.000000
1125      34.500000
1293       8.000000
1312      38.360000
1374      12.000000
1439       5.000000
1443      80.300000
1571     220.000000
1656      16.000000
1703     125.000000
2272       4.500000
2328      10.100000
2496       6.900000
2627     137.500000
2685       6.500000
2719      24.790172
3055      12.000000
3127      35.194393
3195      17.000000
3387      85.860220
3517       9.000000
3612      38.000000
3774      16.499999
3842      12.500000
            ...
9816      11.800000
9836       2.750000
9837      72.700000
9876       8.500100
9878       2.500000
9989      12.000000
9993      25.000000
10053      2.300000
10506     33.000000
10558     24.500000
10797     28.400000
10816     48.100000
10881      4.000000
10891      1.000000
10918      8.660000
10966      9.550000
10992     21.000000
11676      7.000000
11712     73.884800
11799      6.000000
11831     10.000000
11879      7.000000
12219      7.634742
12273      8.500000
12521     10.500000
12751     17.500000
12895     23.950000
12985     35.000000
13030      1.200000
13205     49.900000
Name: funding_total_usd, Length: 111, dtype: float64, 61        64.567194
129       13.600000
197       75.000000
213       25.000000
276        6.000000
297       19.000000
460       59.450091
506       51.311845
938       29.638309
1183      60.000000
1218      82.230000
1440       3.113168
1544      13.300000
1567      75.500000
1630      13.400000
1856      26.500000
1940      23.470000
2016      72.110889
2066      38.850000
2150      39.064207
2153       4.000000
2194      38.000000
2748      29.310000
2827      46.000000
2874      71.426633
2950      22.000000
2953      34.010000
3243       0.050000
3382       7.060006
3586      15.000000
            ...
9765      16.000000
9988      48.200000
10284      6.100000
10286      1.225000
10522     13.000000
10614    130.000000
10630      1.392573
10728      3.610000
10847     23.754000
11068     60.950000
11167      6.500000
11301      7.770100
11640     20.000000
11660     10.000000
11692     16.000000
11888     10.400000
12013      7.250000
12088     15.215000
12177     15.000000
12259     61.120000
12615      8.500000
12623     14.770000
12645      2.500000
12740    100.948403
12817      7.400000
12888     17.600000
13105     10.000000
13374      6.000000
13385     12.000000
13671     87.000000
Name: funding_total_usd, Length: 114, dtype: float64, 215        22.500000
254       176.275000
793         1.358979
836        43.901134
903         0.350000
959        28.100000
985        20.000000
1007       50.800000
1026        4.000000
1079        8.771500
1088        8.590000
1219        3.387542
1347       10.300000
1498        1.000000
1528      177.683533
1672       13.250000
1835        5.000000
1958       14.450000
1983        5.000000
2044       16.400000
2148       99.614399
2180        3.500000
2261       19.000000
2503     5820.000000
2662        2.900000
2846       93.000000
2882        4.000000
3318        2.190000
3389       60.900000
3390       69.050788
            ...
10185      32.000000
10240       7.720000
10361      84.000000
10488       9.100000
10501       7.000000
10787       5.700000
10971      22.300000
11242      40.000000
11434       0.600000
11461      12.840000
11690      15.000000
11812      54.597734
12007       4.000000
12014       7.250000
12510       7.733619
12550      18.973011
12557      45.226149
12641      18.508487
12747      12.700000
12822      12.000000
12849      37.600000
12926       2.700000
12990      22.000000
13152       5.000000
13165       8.000000
13252      12.000000
13257      59.000000
13356      12.200000
13484      12.500000
13583      27.138500
Name: funding_total_usd, Length: 131, dtype: float64, 37         0.020000
65        38.064570
102      118.000000
539        9.300000
664       34.600000
672      125.000000
674        7.000000
739      173.000000
1023      25.500000
1139       1.100000
1224      14.500000
1263      60.000000
1409       9.000000
1454      21.700000
1523     129.000000
1548      35.750000
1570       2.500000
1576      10.000000
1691       0.500000
1877      28.426018
1896       5.800000
1977      10.000000
2026     250.000000
2205       2.398464
2206       8.500000
2338       1.200000
2537       5.610000
2667       6.900000
2892      13.600000
2961      65.628255
            ...
10877      6.000000
10904     14.500000
10930    178.149887
10952      3.000000
10964     10.000000
11289     37.339356
11300     25.000000
11309     78.500000
11493     16.325814
11730      5.500000
11844      4.900000
11872    131.190000
11903     38.000000
12244     37.000000
12254     12.050000
12568      6.500000
12692     66.999997
12837     10.660000
12957      3.500000
12971      1.100000
13176     17.385483
13199      1.300000
13235     50.000000
13246     25.500100
13298      5.393366
13381     38.000000
13396      6.788572
13411      6.500000
13428      3.000000
13574      1.000000
Name: funding_total_usd, Length: 151, dtype: float64, 53         4.000000
69        60.000000
145        4.045500
406       30.455361
410        9.028626
440      276.108581
593        1.500000
605       12.800000
679        4.313980
776        4.100000
856        2.500000
1013      53.000000
1035      28.787632
1107       5.000000
1123     317.300000
1153       9.500000
1215      80.000000
1513       1.100000
1552      22.500000
1782     558.950000
1822      20.000000
1858       2.200000
2071      67.192715
2104      12.600000
2227      17.517561
2386      17.500000
2440       4.180000
2737      12.600000
2784     109.800000
2800       3.500000
            ...
11722    101.580000
11890     23.416000
11970      8.500000
12071     56.351387
12240      3.000000
12321     16.000000
12378     25.000000
12466     58.500000
12622     17.654216
12651     28.787685
12678      2.500000
12785     65.000000
12826     28.650000
12827    136.415300
12838      4.359346
12942     19.210000
12956     31.500000
13031     10.000000
13051     91.466131
13097     15.495815
13169     39.750000
13222     42.500000
13344     40.540723
13352     21.500000
13357     85.870000
13383     46.800000
13394     11.035000
13419     18.000000
13491     42.000000
13630     35.000000
Name: funding_total_usd, Length: 159, dtype: float64, 82         6.528902
87         9.850000
128        7.618249
150       28.500000
181       30.500000
230        0.150000
404       18.527468
409       41.000016
411        0.250000
497       11.043722
565        0.200000
670      144.400000
720        3.200000
764       87.900000
785      111.700000
790        0.018000
804       11.700000
813        7.000000
837       33.000000
935       13.425000
1031       1.681068
1037      30.000000
1045       0.050000
1097      10.349192
1141     109.772047
1602       6.536608
1637      25.732374
1651       4.667517
1662       4.000000
1774      29.805235
            ...
12479      5.000000
12609     29.500000
12624     16.100000
12712      3.598474
12723      8.300000
12725    114.260328
12779     37.064136
12813     37.535089
12880      4.000000
12924      5.000000
12930      0.550000
12988     20.686530
12994     18.400000
13001      5.300000
13022      0.350000
13117     31.065000
13125     35.670000
13229     29.800000
13258      1.000000
13260      0.605000
13262     63.000001
13330      2.000000
13336      7.700000
13363     21.700000
13379      3.000000
13401     41.752000
13477      2.000000
13521      3.200000
13673      0.050000
13693     28.300000
Name: funding_total_usd, Length: 233, dtype: float64, 56         1.011601
57         5.000000
62         3.393925
105        6.000000
151       25.000000
157       30.000000
508       27.000000
522      118.400035
592       16.000000
713        2.550000
757        9.600000
786       80.800000
808       56.000000
909        5.000000
1003       0.040000
1060      71.100000
1120      10.800000
1131      23.800000
1156      36.349780
1190      14.450000
1233       5.300001
1345       3.486023
1509       3.000000
1580      40.500000
1586      28.000000
1628       1.249990
1633       5.850000
1760      24.499999
1773       0.015000
1859      61.900000
            ...
11404      0.250000
11429     13.000000
11735      0.800000
11749    302.312497
11778      7.825000
11917      3.000000
12174     35.200000
12284      2.130000